package mocks

import (
	"Weather-Monster/models"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

//CreateCity provides a mock function with given fields: ctx, c
func (m *Repository) CreateCity(ctx context.Context, c *models.Cities) error {
	ret := m.Called(ctx, c)
	var err error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Cities) error); ok {
		err = rf(ctx, c)
	} else {
		err = ret.Error(0)
	}

	return err
}

//UpdateCity provides a mock function with given fields: ctx, c
func (m *Repository) UpdateCity(ctx context.Context, c *models.Cities) error {
	ret := m.Called(ctx, c)

	var err error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Cities) error); ok {
		err = rf(ctx, c)
	} else {
		err = ret.Error(0)
	}

	return err
}

//DeleteCity provides a mock function with given fields: ctx, id
func (m *Repository) DeleteCity(ctx context.Context, id int64) error {
	ret := m.Called(ctx, id)

	var err error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		err = rf(ctx, id)
	} else {
		err = ret.Error(0)
	}

	return err
}
