package mocks

import (
	"Weather-Monster/models"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// TempUsecase is an autogenerated mock type for the Usecase type
type TempUsecase struct {
	mock.Mock
}

//CreateTemperature provides a mock function with given fields: _a0, _a1
func (m *TempUsecase) CreateTemperature(c context.Context, tmp *models.Temperatures) error {
	ret := m.Called(c, tmp)

	var err error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Temperatures) error); ok {
		err = rf(c, tmp)
	} else {
		err = ret.Error(0)
	}

	return err
}

// GetCityByID provides a mock function with given fields: ctx, ctyID
func (m *TempUsecase) GetCityByID(ctx context.Context, ctyID int64) (*models.Cities, error) {
	ret := m.Called(ctx, ctyID)

	var err *models.Cities
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Cities); ok {
		err = rf(ctx, ctyID)
	} else {
		if ret.Get(0) != nil {
			err = ret.Get(0).(*models.Cities)
		}
	}

	var cerr error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		cerr = rf(ctx, ctyID)
	} else {
		cerr = ret.Error(1)
	}

	return err, cerr
}
